/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // CivicIssue AI Design System - Material You "Trust Blue"
        primary: "#004d99",
        "primary-container": "#1565c0",
        "on-primary": "#ffffff",
        "on-primary-container": "#dae5ff",
        "primary-fixed": "#d6e3ff",
        "primary-fixed-dim": "#a9c7ff",
        "on-primary-fixed": "#001b3d",
        "on-primary-fixed-variant": "#00468c",
        "inverse-primary": "#a9c7ff",
        secondary: "#5c5f60",
        "secondary-container": "#dee0e2",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#606365",
        "secondary-fixed": "#e1e2e4",
        "secondary-fixed-dim": "#c5c7c8",
        "on-secondary-fixed": "#191c1e",
        "on-secondary-fixed-variant": "#444749",
        tertiary: "#813900",
        "tertiary-container": "#a64c00",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ffdece",
        "tertiary-fixed": "#ffdbc9",
        "tertiary-fixed-dim": "#ffb68c",
        "on-tertiary-fixed": "#321200",
        "on-tertiary-fixed-variant": "#753400",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        surface: "#fcf9f8",
        "surface-dim": "#dcd9d9",
        "surface-bright": "#fcf9f8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "surface-container": "#f0eded",
        "surface-container-high": "#eae7e7",
        "surface-container-highest": "#e5e2e1",
        "on-surface": "#1c1b1b",
        "on-surface-variant": "#424752",
        "inverse-surface": "#313030",
        "inverse-on-surface": "#f3f0ef",
        outline: "#727783",
        "outline-variant": "#c2c6d4",
        "surface-tint": "#005db7",
        "surface-variant": "#e5e2e1",
        background: "#fcf9f8",
        "on-background": "#1c1b1b",
        // AI accent
        "ai-accent": "#7c4dff",
        "ai-accent-light": "#ede7f6",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.25rem",
        md: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        base: "4px",
        gutter: "20px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["32px", { lineHeight: "40px", fontWeight: "700", letterSpacing: "-0.02em" }],
        "headline-lg": ["24px", { lineHeight: "32px", fontWeight: "600", letterSpacing: "-0.01em" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "600", letterSpacing: "0.05em" }],
        "table-data": ["13px", { lineHeight: "18px", fontWeight: "400" }],
      },
      boxShadow: {
        card: "0px 2px 4px rgba(0,0,0,0.05)",
        "card-hover": "0px 8px 24px rgba(0,0,0,0.12)",
        modal: "0px 16px 48px rgba(0,0,0,0.18)",
      },
      keyframes: {
        "fade-in": { from: { opacity: 0, transform: "translateY(8px)" }, to: { opacity: 1, transform: "translateY(0)" } },
        "slide-in": { from: { transform: "translateX(-100%)" }, to: { transform: "translateX(0)" } },
        "pulse-dot": { "0%,100%": { opacity: 1 }, "50%": { opacity: 0.4 } },
      },
      animation: {
        "fade-in": "fade-in 0.3s ease-out",
        "slide-in": "slide-in 0.3s ease-out",
        "pulse-dot": "pulse-dot 1.5s ease-in-out infinite",
      },
    },
  },
  plugins: [],
}
